FROM registry.thunisoft.com:5000/thunisoft/centos-xfce-vnc-arm64:1.0
USER 0
RUN yum install -y mesa-libGLU \
 && yum --skip-broken -y install libqt* \ 
 && yum -y install gcc \
 && yum -y install gcc-c++ \
 && yum -y install make \
 && yum -y install libXss* \
 && yum -y install wget \
 && yum -y install python36 \
 && yum install -y  qt5-qttools-devel \
 && yum install -y libpng* \
 && yum clean all \
 && pip3 install python-multipart jinja2 aiofiles fastapi uvicorn apscheduler
RUN cd /home \
 && localedef -c -f UTF-8 -i zh_CN zh_CN.utf8 \
 && curl -O http://172.18.12.223:22062/solo/techgroup/0914/resource-arm.tar.gz \
 && tar zxvf resource-arm.tar.gz \ 
 && pip3 install pywpsrpc-2.2.0-cp36-cp36m-linux_aarch64.whl \
 && tar zxvf fonts-cn.tar.gz \
 && rm -rf /usr/share/fonts/* \
 && mv fonts/* /usr/share/fonts \
 && rpm -ivh /home/wps-office-11.1.0.9719-1.aarch64.rpm \
 && tar zxvf wps-so.tar.gz \
 && cp /home/so/*.so /opt/kingsoft/wps-office/office6/ \
 && rm -rf /home/so/ \
 && rm wps-so.tar.gz \
 && tar zxvf gcc-4.9.3.tar.gz \
 && mkdir build-gcc \
 && cd build-gcc \
 && ../gcc-4.9.3/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++ --enable-plugin --enable-initfini-array --disable-libgcj --enable-gnu-indirect-function --disable-multilib \
 && make -j8 \
 && make install \
 && rm -rf /home/*
RUN curl -O http://172.18.12.223:22062/solo/techgroup/0914/code29.tar.gz \ 
 && tar zxvf code29.tar.gz 
RUN  cd .config/ \ 
 && curl -O http://172.18.12.223:22062/solo/techgroup/0914/Kingsoft.tar.gz \
 && rm -rf Kingsoft/ \
 && tar zxvf Kingsoft.tar.gz \
 && rm -rf  Kingsoft.tar.gz
ENV TZ=Asia/Shanghai
ENV VNC_PW=6789@jkl
EXPOSE 5678
CMD python3 schedule.py
